'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PastLinkGroundControl.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property arrow_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bee_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bee_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bigkey_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bigkey_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bird_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bird_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueboomer_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueboomer_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bluemail_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bluemail_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bluepotion_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bluepotion_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bomb_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bomb_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bombos_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bombos_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property book_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boots_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boots_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle1_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle1_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle2_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle2_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle3_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle3_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bottle4_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bottle4_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brazierlit_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brazierlit_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brazierpartlit_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brazierpartlit_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brazierunlit_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brazierunlit_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property buffenemy_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("buffenemy_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bugnet_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bugnet_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bunny_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bunny_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property canebyrna_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("canebyrna_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property canesomaria_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("canesomaria_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cape_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cape_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chest_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chest_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property compass_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("compass_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property confused_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("confused_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property consumables_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("consumables_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cucco_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cucco_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cuccostorm_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cuccostorm_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property death_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("death_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property downgrade_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("downgrade_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property enemydumb_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemydumb_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property enemyhealth_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemyhealth_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property enemyintelligence_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemyintelligence_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property enemynormal_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemynormal_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property equipment_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("equipment_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ether_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ether_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fairy_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fairy_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fast_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fast_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property firerod_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("firerod_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property flippers_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("flippers_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property give_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("give_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gloves_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gloves_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property greenmail_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greenmail_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property greenpotion_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("greenpotion_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property halfmagic_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("halfmagic_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hammer_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hammer_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heart_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heart1_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart1_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heart10_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart10_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heart11_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart11_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heart12_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart12_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heart13_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart13_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heart2_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart2_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heart3_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart3_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heart4_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart4_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heart5_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart5_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heart6_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart6_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heart7_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart7_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heart8_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart8_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heart9_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart9_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece1_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece1_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece10_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece10_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece11_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece11_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece12_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece12_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece13_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece13_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece14_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece14_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece15_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece15_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece16_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece16_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece17_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece17_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece18_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece18_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece19_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece19_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece2_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece2_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece20_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece20_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece21_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece21_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece22_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece22_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece23_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece23_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece24_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece24_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece3_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece3_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece4_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece4_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece5_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece5_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece6_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece6_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece7_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece7_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece8_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece8_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heartpiece9_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heartpiece9_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property hookshot_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hookshot_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icerod_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icerod_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property invincible_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invincible_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property invisible_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invisible_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property lamp_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lamp_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property magic_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("magic_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property map_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("map_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mirror_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mirror_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mushroom_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mushroom_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nerfenemy_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nerfenemy_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nobigkey_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nobigkey_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nobird_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nobird_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noblueboomer_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noblueboomer_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nobomb_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nobomb_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nobombos_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nobombos_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nobook_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nobook_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noboots_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noboots_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nobottles_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nobottles_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nobow_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nobow_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nobugnet_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nobugnet_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nocanebyrna_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nocanebyrna_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nocanesomaria_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nocanesomaria_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nocape_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nocape_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nochest_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nochest_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nocompass_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nocompass_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noether_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noether_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nofirerod_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nofirerod_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noflippers_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noflippers_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noglove_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noglove_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nohalfmagic_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nohalfmagic_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nohammer_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nohammer_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noheartpieces_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noheartpieces_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nohearts_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nohearts_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nohookshot_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nohookshot_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noicerod_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noicerod_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noinvincible_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noinvincible_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nolamp_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nolamp_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nomap_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nomap_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nomirror_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nomirror_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nomushroom_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nomushroom_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noocarina_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noocarina_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nopearl_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nopearl_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nopowder_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nopowder_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noquake_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noquake_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noredboomer_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noredboomer_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property normal_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("normal_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property normalbow_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("normalbow_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noshield_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noshield_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noshovel_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noshovel_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nosmallkey_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nosmallkey_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property nosword_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("nosword_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ocarinafake_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ocarinafake_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ocarinareal_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ocarinareal_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property orbswitch_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orbswitch_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pearl_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pearl_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pot_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pot_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property powder_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("powder_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property powerglove_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("powerglove_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property quake_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quake_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redboomer_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redboomer_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redmail_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redmail_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property redpotion_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redpotion_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rupee_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rupee_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shield1_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shield1_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shield2_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shield2_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shield3_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shield3_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shovel_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shovel_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property silverbow_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("silverbow_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property skull_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skull_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property slow_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("slow_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property smallkey_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallkey_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property superbee_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("superbee_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property surprise_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("surprise_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sword1_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sword1_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sword2_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sword2_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sword3_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sword3_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property sword4_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sword4_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property take_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("take_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property titanmitt_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("titanmitt_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property upgrade_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("upgrade_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
